# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15dcce25141f68edea076de2c2521f60e5060eeeae785bc91a79e7de2468cd7727b416cf85eb00b0f0f859d7fb424df5907155e0db3cf301b1d98a5637206920

test:
  secret_key_base: b69dafeed5395ccefe29af1d620ea75f0a404e4941945bb85bf7334817aa14289273016438e10179706507a91fb68ce1400e18459bf159e75aa8f5d6bf394a70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
